---
scenario:
  name: ubuntu-focal
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ps-node1-ubuntu-focal
    private_ip: ${PS_NODE1_IP}
    region: us-west-2
    image: ami-09dd2e08d601bff67
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-ps-worker
  - name: ps-node2-ubuntu-focal
    private_ip: ${PS_NODE2_IP}
    region: us-west-2
    image: ami-09dd2e08d601bff67
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-ps-worker
  - name: ps-node3-ubuntu-focal
    private_ip: ${PS_NODE3_IP}
    region: us-west-2
    image: ami-09dd2e08d601bff67
    vpc_subnet_id: subnet-0430e63d7cdbcd237
    instance_type: t2.micro
    ssh_user: ubuntu
    root_device_name: /dev/sda1
    instance_tags:
      iit-billing-tag: jenkins-ps-worker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../../../playbooks/create.yml
    destroy: ../../../../playbooks/destroy.yml
    prepare: ../../../playbooks/prepare.yml
    converge: ../../playbooks/playbook.yml
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
    s: true
    junitxml: report.xml
  lint:
    name: flake8
